### ISSUE TITLE
src/greenlet/greenlet.h:42:5: error: unknown type name ‘CFrame’

### ISSUE THREAD

**Issue by allen-munsch** [python-greenlet/greenlet#295]
Anyone know off hand how to install `CFrame` header stuff? 

Was getting hung up on trying to find which version of gcc, and headers to use for `2.0.0.a1` and `Python 3.11.0a6+`

```
02:31:14 (venv_3_11_dev) jm@jm asdf ±|AA-1545-jm-1 ✗|→ python --version
Python 3.11.0a6+

02:35:44 (venv_3_11_dev) jm@jm asdf ±|AA-1545-jm-1 ✗|→ cat requirements.txt | grep greenlet
-e git+https://github.com/python-greenlet/greenlet.git@2.0.0a1#egg=greenlet

02:35:59 (venv_3_11_dev) jm@jm asdf ±|AA-1545-jm-1 ✗|→ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.3 LTS
Release:	20.04
Codename:	focal
```

- https://stackoverflow.com/questions/71607693/src-greenlet-greenlet-h425-error-unknown-type-name-cframe
- https://github.com/python-greenlet/greenlet/pull/280

**Comment by jamadden** [comment]
Versions of greenlet prior to 2.0a2 (released yesterday) do not work with Python 3.11a6.
