### ISSUE TITLE
0.4.6 Won't Compile Under Python 2.5

### ISSUE THREAD

**Issue by jamadden** [python-greenlet/greenlet#82]
In commit 6a2d69dc1de25d7a623b5cfd835d13bc36eab8d0 a call to the function `PyLong_FromSsize_t` was added, but according to [the documentation](https://docs.python.org/2/c-api/long.html#c.PyLong_FromSsize_t) this function is only available in 2.6 and above.

This leads to the following compile error:
```
greenlet.c: In function ‘green_get_stack_saved’:
greenlet.c:1232:2: warning: implicit declaration of function ‘PyLong_FromSsize_t’ [-Wimplicit-function-declaration]
greenlet.c:1232:2: warning: return makes pointer from integer without a cast [enabled by default]
```

And of course the resulting `ImportError`:
```
python2.5 -c 'import greenlet; print (greenlet, greenlet.__version__)'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: /usr/lib/python2.5/site-packages/greenlet.so: undefined symbol: PyLong_FromSsize_t
```

**Comment by snaury** [comment]
Confirmed the fix works on 2.4 and 2.5, thanks!
