### ISSUE TITLE
Greenlet fails to build on MSVC on Python 3.14

### ISSUE THREAD

**Issue by encukou** [python-greenlet/greenlet#448]
(Filing for awareness, and possible coordination. Fixing this is not on my immediate TODO list, though I'd be willing to mentor/guide a C programmer interested in adding the APIs that Greenlet needs to CPython.)

As seen in a [SQLAlchemy build](https://github.com/sqlalchemy/sqlalchemy/actions/runs/15428059616/job/43419762342) from [trying to build with 3.14](https://mastodon.social/@zzzeek@hachyderm.io/114625958300396886), Greenlet fails to build because it uses internal CPython headers, which now use a C feature that's not in C++:
```
  Building wheel for greenlet (pyproject.toml) did not run successfully.
[...]
  "[...]\cl.exe" [...] /Tpsrc/greenlet/greenlet.cpp [...] /std:c++20

  [...]\pycore_stackref.h(253): error C4576: a parenthesized type followed by an initializer list is a non-standard explicit type conversion syntax
```
