### ISSUE TITLE
Error while building wheel for greenlet

### ISSUE THREAD

**Issue by pannet1** [python-greenlet/greenlet#296]
`
Building wheels for collected packages: greenlet
  Building wheel for greenlet (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [17 lines of output]
      running bdist_wheel
      running build
      running build_ext
      building 'greenlet' extension
      creating build
      creating build/temp.linux-x86_64-3.10
      gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -march=x86-64 -mtune=generic -O3 -pipe -fno-plt -fexceptions -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security -fstack-clash-protection -fcf-protection -flto=auto -ffat-lto-objects -march=x86-64 -mtune=generic -O3 -pipe -fno-plt -fexceptions -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security -fstack-clash-protection -fcf-protection -flto=auto -march=x86-64 -mtune=generic -O3 -pipe -fno-plt -fexceptions -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security -fstack-clash-protection -fcf-protection -flto=auto -fPIC -I/home/pannet1/.virtualenvs/odoo-15.0.post20220328/include -I/usr/include/python3.10 -c greenlet.c -o build/temp.linux-x86_64-3.10/greenlet.o
      greenlet.c: In function ‘g_calltrace’:
      greenlet.c:566:17: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘use_tracing’; did you mean ‘tracing’?
        566 |         tstate->use_tracing = 0;
            |                 ^~~~~~~~~~~
            |                 tracing
      greenlet.c:569:17: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘use_tracing’; did you mean ‘tracing’?
        569 |         tstate->use_tracing = (tstate->tracing <= 0 &&
            |                 ^~~~~~~~~~~
            |                 tracing
      error: command '/usr/bin/gcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for greenlet
  Running setup.py clean for greenlet
Failed to build greenlet
Installing collected packages: XlsxWriter, pyusb, pytz, python-stdnum, pyserial, polib, passlib, num2words, greenlet, chardet, appdirs, xlrd, Werkzeug, urllib3, qrcode, python-dateutil, pydot, pyasn1-modules, psycopg2, psutil, Pillow, MarkupSafe, lxml, libsass, idna, docutils, defusedxml, decorator, Babel, requests, reportlab, python-ldap, ofxparse, Jinja2, gevent, freezegun, pyopenssl, ebaysdk, zeep
  Attempting uninstall: XlsxWriter
    Found existing installation: XlsxWriter 3.0.3
ERROR: Exception:
Traceback (most recent call last):
  File "/home/pannet1/.virtualenvs/odoo-15.0.post20220328/lib/python3.10/site-packages/pip/_internal/cli/base_command.py", line 167, in exc_logging_wrapper
    status = run_func(*args)
  File "/home/pannet1/.virtualenvs/odoo-15.0.post20220328/lib/python3.10/site-packages/pip/_internal/cli/req_command.py", line 205, in wrapper
    return func(self, options, args)
  File "/home/pannet1/.virtualenvs/odoo-15.0.post20220328/lib/python3.10/site-packages/pip/_internal/commands/install.py", line 405, in run
    installed = install_given_reqs(
  File "/home/pannet1/.virtualenvs/odoo-15.0.post20220328/lib/python3.10/site-packages/pip/_internal/req/__init__.py", line 68, in install_given_reqs
    uninstalled_pathset = requirement.uninstall(auto_confirm=True)
  File "/home/pannet1/.virtualenvs/odoo-15.0.post20220328/lib/python3.10/site-packages/pip/_internal/req/req_install.py", line 637, in uninstall
    uninstalled_pathset = UninstallPathSet.from_dist(dist)
  File "/home/pannet1/.virtualenvs/odoo-15.0.post20220328/lib/python3.10/site-packages/pip/_internal/req/req_uninstall.py", line 554, in from_dist
    for script in dist.iterdir("scripts"):
  File "/home/pannet1/.virtualenvs/odoo-15.0.post20220328/lib/python3.10/site-packages/pip/_internal/metadata/pkg_resources.py", line 156, in iterdir
    if not self._dist.isdir(name):
  File "/home/pannet1/.virtualenvs/odoo-15.0.post20220328/lib/python3.10/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2816, in __getattr__
    return getattr(self._provider, attr)
AttributeError: 'PathMetadata' object has no attribute 'isdir'
`

**Comment by yannfill** [comment]
Greenlet 1.1.2 fails to build with python 3.10:
```
Building wheels for collected packages: greenlet
  Building wheel for greenlet (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /srv/modoboa/env/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/srv/modoboa/tmp/pip-install-opbd123t/greenlet_278ddb4fc2f349ad831e00b3bb3691cf/setup.py'"'"'; __file__='"'"'/srv/modoboa/tmp/pip-install-opbd123t/greenlet_278ddb4fc2f349ad831e00b3bb3691cf/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /srv/modoboa/tmp/pip-wheel-uwhw8e11
       cwd: /srv/modoboa/tmp/pip-install-opbd123t/greenlet_278ddb4fc2f349ad831e00b3bb3691cf/
  Complete output (17 lines):
  running bdist_wheel
  running build
  running build_ext
  building 'greenlet' extension
  creating build
  creating build/temp.linux-x86_64-3.10
  gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -march=x86-64 -mtune=generic -O3 -pipe -fno-plt -fexceptions -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security -fstack-clash-protection -fcf-protection -flto=auto -ffat-lto-objects -march=x86-64 -mtune=generic -O3 -pipe -fno-plt -fexceptions -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security -fstack-clash-protection -fcf-protection -flto=auto -march=x86-64 -mtune=generic -O3 -pipe -fno-plt -fexceptions -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security -fstack-clash-protection -fcf-protection -flto=auto -fPIC -I/srv/modoboa/env/include -I/usr/include/python3.10 -c greenlet.c -o build/temp.linux-x86_64-3.10/greenlet.o
  greenlet.c: In function 'g_calltrace':
  greenlet.c:566:17: error: 'PyThreadState' {aka 'struct _ts'} has no member named 'use_tracing'; did you mean 'tracing'?
    566 |         tstate->use_tracing = 0;
        |                 ^~~~~~~~~~~
        |                 tracing
  greenlet.c:569:17: error: 'PyThreadState' {aka 'struct _ts'} has no member named 'use_tracing'; did you mean 'tracing'?
    569 |         tstate->use_tracing = (tstate->tracing <= 0 &&
        |                 ^~~~~~~~~~~
        |                 tracing
  error: command '/usr/bin/gcc' failed with exit code 1
  ----------------------------------------
  ERROR: Failed building wheel for greenlet
  Running setup.py clean for greenlet
Failed to build greenlet
```

**Comment by jamadden** [comment]
Incorrect. greenlet 1.1.2 builds fine with Python 3.10. I know this for a fact because there are binary wheels of greenlet 1.1.2 for Python 3.10 on PyPI. 

Also, the line numbers in your error do not line up at all with greenlet 1.1.2, or 1.1.1 or even 1.1.0. The only version that matches is 0.4.17.

**Comment by yannfill** [comment]
You are right. You can close #297 too.
